Powershell -ExecutionPolicy Bypass -File "D:\_A\Configuration\Python\Cisco\cisco.py" 
Read-Host -Prompt "Press Enter to exit"
Write-Output "Bonjour, cela et une modification de BRAHIM DAHOU"
Write-Output "Bonjour, cela et une modification de BRAHIM DAHOU"
Write-Output "Bonjour, cela et une modification de BRAHIM DAHOU"